### ISSUE TITLE
<!DOCTYPE html> Syntax Error: invalid syntax

### ISSUE THREAD

**Issue by imperfectscientist** [olibclarke/coot-trimmings#1]
Hi Oli,

I've just tried to install your coot bindings. But, although coot itself opens, the "Custom" menu doesn't show up and in the terminal window, I get the following error

`Running python script /home/mine/.coot-preferences/oli_custom.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mine/.coot-preferences/oli_custom.py", line 6
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
`
I'm using coot-0.9.1-pre. Any idea how I can fix this? Seems like an incompatibility between python versions of the bindings and coot. 

Thank you,

Vamsee

**Comment by imperfectscientist** [comment]
Sorry, never mind. I used the coot-trimmings.py from your NYSBC tutorial and that fixed the issue. 

Thank you again for the trimmings. Very useful.

Vamsee
